//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetService.Helpers {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Procedures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Procedures() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VetService.Helpers.Procedures", typeof(Procedures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AgendarCita.
        /// </summary>
        public static string AgendarCita {
            get {
                return ResourceManager.GetString("AgendarCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AgregarHistoriaClinica.
        /// </summary>
        public static string AgregarHistoriaClinica {
            get {
                return ResourceManager.GetString("AgregarHistoriaClinica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EspecialidadVeterinario.
        /// </summary>
        public static string EspecialidadVeterinario {
            get {
                return ResourceManager.GetString("EspecialidadVeterinario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a InfoPaciente.
        /// </summary>
        public static string InfoPaciente {
            get {
                return ResourceManager.GetString("InfoPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a InfoVeterinario.
        /// </summary>
        public static string InfoVeterinario {
            get {
                return ResourceManager.GetString("InfoVeterinario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RegistroPaciente.
        /// </summary>
        public static string RegistroPaciente {
            get {
                return ResourceManager.GetString("RegistroPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VerAgendaVeterinario.
        /// </summary>
        public static string VerAgendaVeterinario {
            get {
                return ResourceManager.GetString("VerAgendaVeterinario", resourceCulture);
            }
        }
    }
}
